introduce a simple batcher for awspubsub_test
Confusingly, this makes the test fail in record mode.
[ ~/gocloud.dev/pubsub/awspubsub ] go test -record
--- FAIL: TestConformance (8.92s)
    --- FAIL: TestConformance/TestSendReceiveTwo (3.66s)
        replay.go:69: Recording into golden file testdata/TestConformance/TestSendReceiveTwo
        drivertest.go:233: sub #1: {[]*pubsub.Message}[1->?]:
            -: &pubsub.Message{Body: []uint8{0x32}, Metadata: map[string]string{"a": "2"}, ack: (func())(0x014c6a80), isAcked: true}
            +: <non-existent>
            {[]*pubsub.Message}[?->1]:
            -: <non-existent>
            +: &pubsub.Message{Body: []uint8{0x31}, Metadata: map[string]string{"a": "1"}}
FAIL
exit status 1