internal/cmd/gocdk: fix crash on deploying newly built image
A shadowed variable caused the build to occur, but the image reference
to be ignored by the rest of the deploy process. The error would look
like:

Error: gocdk deploy: cloud run launch: docker tag: docker push: Error parsing reference: "" is not a valid repository/tag: invalid reference format